import { AnimalProps } from '../src/utils/models'

export const animals: AnimalProps[] = [
  {
    id: 1,
    nombre: 'First Animal',
    tipo: 'Gato',
    color: 'Cafe',
    edad: '9 Meses',
    estado: 'Adopcion',
    genero: 'Hembra',
    desc_fisica: 'Lorem Ipsum Lorem Ipsum',
    desc_personalidad: 'Lorem Ipsum in person lorem Ipsum',
    desc_adicional: 'Lorem ipsum dolor sit am',
    esterilizado: 1,
    vacunas: 1,
    imagen: '',
    equipo: '',
    region: 'RM',
    comuna: 'Puente Alto',
    url: '',
  },
  {
    id: 2,
    nombre: 'Second Animal',
    tipo: 'Perro',
    color: 'Negro',
    edad: '5 Meses',
    estado: 'Adopcion',
    genero: 'Macho',
    desc_fisica: 'Lorem Ipsum Lorem Ipsum',
    desc_personalidad: 'Lorem Ipsum in person lorem Ipsum',
    desc_adicional: 'Lorem ipsum dolor sit am',
    esterilizado: 1,
    vacunas: 1,
    imagen: '',
    equipo: '',
    region: 'RM',
    comuna: 'Puente Alto',
    url: '',
  },
  {
    id: 3,
    nombre: 'Third Animal',
    tipo: 'Conejo',
    color: 'Plateado',
    edad: '4 Meses',
    estado: 'Adopcion',
    genero: 'Hembra',
    desc_fisica: 'Lorem Ipsum Lorem Ipsum',
    desc_personalidad: 'Lorem Ipsum in person lorem Ipsum',
    desc_adicional: 'Lorem ipsum dolor sit am',
    esterilizado: 1,
    vacunas: 1,
    imagen: '',
    equipo: '',
    region: 'RM',
    comuna: 'Santiago',
    url: '',
  },
]
